# services.yaml
vacuum_action:
  fields:
    command:
      required: true
      example: "dock"

vacuum_clean:
  fields:
    payload:
      required: true
      example: '{"regions": [{"region_id": "11", "type": "rid"}]}'
